### ISSUE TITLE
Registration failing for identical images

### ISSUE THREAD

**Issue by FritzKagerer** [glichtner/pystackreg#19]
We have two identical images that have been slightly transformed in two different stacks, which we want register one with the other. The images are 1000x1000 pixels

We want to register these two images:
![image](https://user-images.githubusercontent.com/50319149/125666837-90eba1cc-19d4-4ec5-8fdd-621126b44d2b.png)
![image](https://user-images.githubusercontent.com/50319149/125666929-a5a7681f-7195-4eb4-ac42-bf44310a267a.png)

To do the registration we are using the following code:

```python
chunk_last = result[8][j-5]            #image1               
chunk_first = result[9][j]             #image2            
sr = StackReg(StackReg.AFFINE)
tmatrix = sr.register(chunk_last, chunk_first)
chunk_last_transformed = sr.transform(chunk_first, tmatrix)
```
and got the following images:
![image](https://user-images.githubusercontent.com/50319149/125665599-d9cd83f8-e507-4c4f-a207-825176754a51.png)
![image](https://user-images.githubusercontent.com/50319149/125665655-e29adfd1-3839-429c-a054-044c34feca45.png)
As you can see the images are the same but are transformed slightly different in the stacks, image2 (magenta) looks sheared compared to image1.

This is the 2 images superimposed:
![image](https://user-images.githubusercontent.com/50319149/125664926-6e42d2ca-c209-4111-8055-928b5b003b2d.png)

Thanks in advance and thank you for the amazing package!

**Comment by glichtner** [comment]
Dear Fritz,

I have tried to reproduce your problem using the images you provided, but wasn't able to do so: 
``` python
import numpy as np
from pystackreg import StackReg
import imageio
import matplotlib.pyplot as plt

# load images
img1 = imageio.imread('125666837-90eba1cc-19d4-4ec5-8fdd-621126b44d2b.png')
img2 = imageio.imread('125666929-a5a7681f-7195-4eb4-ac42-bf44310a267a.png')

img1 = img1[:, :, 1] # select green channel from "green" image
img2 = img2[:, :, 0] # select red channel from "pink" image

img2 = img2[:img1.shape[0], :img1.shape[1]] # resize img2 to match size of img1

sr = StackReg(StackReg.AFFINE)
tmatrix = sr.register(img2, img1)
transformed = sr.transform(img1, tmatrix)

# overlay of original images
overlay_1_2 = np.stack([img1, img2, np.zeros(img1.shape)], axis=2)
overlay_1_2 /= overlay_1_2.max()

# overlay of transformed and original image
overlay_transformed = np.stack([transformed, img2, np.zeros(img1.shape)], axis=2)
overlay_transformed /= overlay_transformed.max()

f,ax = plt.subplots(1,3, figsize=(27,9))
ax[0].imshow(overlay_1_2)
ax[0].set_title('before transform')
ax[1].imshow(overlay_transformed)
ax[1].set_title('after transform')
ax[2].imshow(img2-transformed)
ax[2].set_title('difference after transform')
plt.tight_layout()
f.patch.set_facecolor('white')
plt.savefig("result.png")
```

Which gave me the following result:
![result](https://user-images.githubusercontent.com/33544440/126455040-6900a495-4c77-46b5-b78d-49678c3e03ac.png)


Let me know if this helps or otherwise please provide the original images that you are trying to transform.

Best,
Gregor

**Comment by Jhanyi** [comment]
Hi Gregor,

We managed to register the above after histogram matching. However, we encounter the same problem on another pair of identical, slightly transformed images even after histogram matching. 

the image pair (already histogram matched) are in the drive below:
[https://drive.google.com/drive/folders/1QTH17n8DNzz3vyxHrNc4q-_J2aEfNZIT?usp=sharing](url)

I would also point out that registration of such identical images was sucessful in the majority, but seem to fail in just a couple.

Thank you very much.

Best,
Hanyi
