### ISSUE TITLE
Translation vs bilinear

### ISSUE THREAD

**Issue by Groomer67** [glichtner/pystackreg#2]
Hi glichtner,

I'm trying out your pystackreg package and so far only affine & bilinear transformations seem to work, with the others, like translation, not having an effect on the movable image. I'd be happy to send you the code / image files I'm working with by email!

Ryan

**Comment by glichtner** [comment]
Hi Ryan,

I'm very sorry for the late answer, I didn't notice the new issues earlier.

Can you maybe post your code here and I will try it on some image that I have? For me translation and rigid body work fine.

Thanks,
Gregor

**Comment by Groomer67** [comment]
I managed to get everything working in the end, thanks anyways!
