### ISSUE TITLE
Registration with translation fails on simple 2-cell images

### ISSUE THREAD

**Issue by Helena-todd** [glichtner/pystackreg#20]
Hi Gregor,

I wish to align (register) an image to its previous timepoint in a timelapse using a StackReg.TRANSLATION. For some reason, the translated image does not seem to be aligned at all, it's rather th opposite: the translation moved the image even further from where it should have been.

```import cv2
import matplotlib.pyplot as plt
import numpy as np
from skimage import io
from pystackreg import StackReg

input_dir = '/Users/ht/Desktop/test_folder_ht/'
img0 = io.imread(input_dir + 'denoised_Lys_C100_Pos0_img_000000003_02-BF_000_xy5_cp_masks.tif')
img1 = io.imread(input_dir + 'denoised_Lys_C100_Pos0_img_000000004_02-BF_000_xy5_cp_masks.tif')

# Binarize the 2 images for alignment:
img0_tmp = np.where(img0 != 0, 1, img0)
img1_tmp = np.where(img1 != 0, 1, img1)

# Register (align) the 2 images and plot superimposed images before and after alignment.
# alignement to the previous image
sr = StackReg(StackReg.TRANSLATION)
translated_img = sr.register_transform(img0_tmp, img1_tmp)

# plot the superimposed images before algnment
plt.figure(figsize=(10, 10))
ax = plt.gca()
im = ax.imshow(img0_tmp+img1_tmp)
plt.suptitle('Superimposed images before alignment', fontsize=16)

# plot the superimposed images after algnment
plt.figure(figsize=(10, 10))
ax = plt.gca()
im = ax.imshow(img0_tmp + translated_img)
plt.suptitle('Superimposed images after alignment', fontsize=16)
```
<img width="523" alt="before_alignment" src="https://user-images.githubusercontent.com/17719754/151935044-4b1597f1-83c4-4b1a-8915-ee3693833385.png">

<img width="514" alt="after_alignment" src="https://user-images.githubusercontent.com/17719754/151935071-34e37a84-09ac-400f-8c89-e2feff95c70c.png">

[test_folder_ht.zip](https://github.com/glichtner/pystackreg/files/7976907/test_folder_ht.zip)

**Comment by georgeoshardo** [comment]
What happens if you try to align the images before binarising?

**Comment by glichtner** [comment]
Dear Helena,

sorry for the very late reply.

I'm unable to reproduce your problem with your data and code (plotting code slightly altered), it actually works perfectly for me:

``` python
import matplotlib.pyplot as plt
import numpy as np
from skimage import io
from pystackreg import StackReg

input_dir='./'
img0 = io.imread(input_dir + 'denoised_Lys_C100_Pos0_img_000000003_02-BF_000_xy5_cp_masks.tif')
img1 = io.imread(input_dir + 'denoised_Lys_C100_Pos0_img_000000004_02-BF_000_xy5_cp_masks.tif')

# Binarize the 2 images for alignment:
img0_tmp = np.where(img0 != 0, 1, img0)
img1_tmp = np.where(img1 != 0, 1, img1)

# Register (align) the 2 images and plot superimposed images before and after alignment.
# alignement to the previous image
sr = StackReg(StackReg.TRANSLATION)
translated_img = sr.register_transform(img0_tmp, img1_tmp)

# plot the superimposed images before algnment
f, ax = plt.subplots(1, 2, figsize=(20, 10))
im = ax[0].imshow(img0_tmp+img1_tmp)
ax[0].set_title('Superimposed images before alignment', fontsize=16)

# plot the superimposed images after algnment
ax[1].imshow(img0_tmp + translated_img)
ax[1].set_title('Superimposed images after alignment', fontsize=16)
plt.savefig("result.png")
```
Result:
![result](https://user-images.githubusercontent.com/33544440/176537803-30e6c8dc-def7-40fe-83e7-bf6f4270f770.png)

Could you try again with your (or my) code and if it still doesn't work, let me know which operating system and python version you are using?

Best,
Gregor

**Comment by glichtner** [comment]
Closing this issue as I haven't heard back and it works for me (see post above).
Feel free to re-open in case you still encounter this issue.
