### ISSUE TITLE
Transformation matrices

### ISSUE THREAD

**Issue by naranji** [glichtner/pystackreg#3]
Hi
Thanks for the neat software. I have a simple question. How can I use the transformation matrices derived by pystackreg to move  a set of coordinates (ex. contour)? As far as I understood, you can only transform image stacks using SR.transform() function.

**Comment by glichtner** [comment]
Hi Naranji,

I'm sorry for the late answer, I didn't notice the new issues earlier!

You can just multiply your coordinates by the transformation matrix to get the transformed coordinates, for example as shown below. Please note that because pystackreg returns a 3x3 affine transformation matrix, you need to add a third dimension to your 2D coordinates that is equal to 1, as shown below (for more information about linear vs affine transformation, see https://alyssaq.github.io/2015/visualising-matrices-and-affine-transformations-with-python/ ):

```python
from matplotlib import pyplot as plt
import numpy as np
from pystackreg import StackReg

img0 = io.imread('some_multiframe_image.tif')
img1 = io.imread('another_multiframe_image.tif')

sr = StackReg(StackReg.RIGID_BODY)
tmat = sr.register(img0[0, :, :], img0[1,:,:])

# create 2D coordinate matrix (note that for the 3x3 affine transformation matrix, 
# which is returned by pystackreg, we need to add a third dimension to the 2D coordinates,
# which equal to 1
p = np.array([[1,120,1], [1,1,1], [250, 1, 1], [250,120,1]]) # 4x3 matrix

# transform coordinates
q = np.dot(p, tmat.T)

# q contains the transformed coordinates
# (again a 4x3 matrix with the 3rd column equal to 1; the first two columns,
# i.e. q[:, 0:2], contain the coordinates)
```

Hope that helps
Gregor

**Comment by orena1** [comment]
Hi @glichtner ,
I've tried the solution that you suggested here, but it looks to me as the numbers have an opposite sign?
See this example:
```python
In [1]: from pystackreg import StackReg
   ...: import numpy as np
   ...: from skimage.morphology import disk
   ...: import matplotlib.pyplot as plt
   ...: sr = StackReg(StackReg.AFFINE)
   ...: 
   ...: data_ref = np.zeros(shape=(518,722))
   ...: data_ref[80:disk(15).shape[0]+80, 50:disk(15).shape[1]+50] = disk(15)
   ...: plt.imshow(data_ref)
   ...: 
   ...: mov_x = 10
   ...: mov_y = 15
   ...: data_mov = np.zeros(shape=(518,722))
   ...: data_mov[80+ mov_x:disk(15).shape[0]+80+mov_x, 50+mov_y:disk(15).shape[1]+50+mov_y] = disk(15)
   ...: plt.imshow(data_mov,alpha=0.3)
   ...: 
   ...: 
   ...: tmat = sr.register(data_ref,data_mov).round(2)
   ...: print(f"tranformation matrix is:\n {tmat}\n")
   ...: print(f"tmat.T is:\n {tmat.T}\n")
   ...: mask_locs = np.nonzero(data_mov)
   ...: p = list(zip(mask_locs[0],mask_locs[1],np.ones(len(mask_locs[0]))))
   ...: 
   ...: q = np.dot(p, tmat.T).astype(int)
   ...: 
   ...: data_new = np.zeros(shape=(518,722))
   ...: data_new[q[:,0],q[:,1]] = 1
   ...: plt.imshow(data_new,alpha=0.2)
   ...: ref_p = np.array(np.nonzero(data_ref))
   ...: print(f"The first non zero point is ref: {ref_p[:,0]}, mov: {p[0]}")
   ...: 
   ...: print("and when multiplied with tmat.T we get that 15 and 10 are added, but they actually need to be subtracted.")
   ...: print(np.dot(p[0], tmat.T).astype(int))
   ...: #
   ...: 
tranformation matrix is:
 [[ 1. -0. 15.]
 [ 0.  1. 10.]
 [ 0.  0.  1.]]

tmat.T is:
 [[ 1.  0.  0.]
 [-0.  1.  0.]
 [15. 10.  1.]]

The first non zero point is ref: [80 65], mov: (90, 80, 1.0)
and when multiplied with tmat.T we get that 15 and 10 are added, but they actually need to be subtracted.
[105  90   1]

```

First, the axis are wrong, the x and y  locations from nonzero are opposite to the transformation matrix, but that is ok and can be a workaround (probably a misunderstanding of the axis by me). But the other thing is the even if I fix it, I need to subtract 15 and 10 from the mov image, and not add.

As far as I understand the transformation matrix should represent the transformation needed on the mov image to get it to the ref image, right? So I should multiply the nonzero from mov to get to the points in ref.

Thanks!

**Comment by orena1** [comment]
Hi @glichtner  did you had a chance to look at my post above?
Thanks

**Comment by PolarBean** [comment]
hi this has helped me a lot, I'm now wondering if it is possible to apply the 4x4 bi-linear transformations to 2D coordinates as well? thank you greatly for your help with this.
