### ISSUE TITLE
pystackreg does not support numpy.2.x

### ISSUE THREAD

**Issue by patquem** [glichtner/pystackreg#35]
Here is the issue encountered when running pystackreg after the install with numpy.2.x.
Could you please look into it and provide a fix?
Thank you

![image](https://github.com/user-attachments/assets/5883dae7-6b81-4c43-9f5f-9bf44983827c)

**Comment by glichtner** [comment]
Hi,
I've added support for numpy2 (in release 0.2.8).
Update pystackreg using e.g.
`pip install pystackreg --upgrade`

Let me know if you have any issues!

**Comment by patquem** [comment]
Hi @glichtner,
My package using pystackreg is now numpy>2 compatible :)
Thank you very much.
