### ISSUE TITLE
Numpy ImportError in Anaconda Windows Environment

### ISSUE THREAD

**Issue by AndrewHerzing** [glichtner/pystackreg#5]
I have an already established Anaconda image processing environment to which I would like to add PyStackReg. I have successfully installed it via `pip`, however, I get an error when I try to import any of the PyStackReg modules.  Specifically, the error is:

`ImportError: numpy.core.multiarray failed to import`

I believe the error is due to the NumPy version that is installed (1.13), but another package is preventing upgrading.  Any suggestions?  Can the code be made more robust against the NumPy version?

**Comment by glichtner** [comment]
Hi Andrew,
sorry for the late reply. If you're still having this problem, could you please attach information about your current python environment, either via
`conda env export --name ENVNAME > envname.yml`

if you are using anaconda, or else via  
`pip freeze > requirements.txt`

Thanks,
Gregor

**Comment by AndrewHerzing** [comment]
I think the problem was NumPy related.  PyStackReg now works with Numpy 1.16, so I guess this issue can be closed.

**Comment by glichtner** [comment]
Alright, thanks for clarification.
