### ISSUE TITLE
Python 3.8 compatible whl

### ISSUE THREAD

**Issue by dbstrasf** [glichtner/pystackreg#6]
Hi, I'm trying to get pystackreg up and running with Python 3.8. Is there any plan to issue a 3.8 compatible whl?

thanks,
Dave

**Comment by glichtner** [comment]
Hi Dave,

sorry for the late reply. Python 3.8 and 3.9 packages for Windows are now on PyPI and also on conda forge.
You can install them via (preferred):
`conda install pystackreg -c conda-forge`
or 
`pip install pystackreg`

Best regards,
Gregor
