### ISSUE TITLE
Coloured tiffs stack registration

### ISSUE THREAD

**Issue by machinedheart10** [glichtner/pystackreg#7]
Hi,

First and foremost, thank you for this wonderful library that you have written.

I am writing this to ask if coloured (3 channels) stack tiffs can be registered and transform from the methods found in this library? Based on the documentation and the tutorials, it seems that image registration can only be applied to single colour channel images, but I would like to confirm if it is true. If so, are there any workarounds? 

Thank you for your time.

**Comment by glichtner** [comment]
Hi,

Generally this is possible but the answer depends a bit on what exactly you mean by registering a 3 channel stack. 
- Do you have a stack with only 3 images, one per color (3 colors x 1 image) and want to align the colored images with each other?
- Or do you have a 3-color stack with multiple images per color (3 colors x N images) and want to align 
  - the N images within each color to each other (but not the 3 colors)?
  - the N images of one color (e.g. green channel) to each other and then apply this transformation to the other 2 color channels?
  - the N images of the 3 colors with each other using information from all 3 colors "simultaneously"?

Gregor

**Comment by machinedheart10** [comment]
Hi Gregor,Thank you for your reply.For my application, I am hoping to align N images of 3 colours with each other using information from all 3 colour simultaneously, what would your proposed direction be?Thank you for your time.  Adriel  From: Gregor LichtnerSent: Thursday, 10 December 2020 8:27 pmTo: glichtner/pystackregCc: machinedheart10; AuthorSubject: Re: [glichtner/pystackreg] Coloured tiffs stack registration (#7) Hi,Generally this is possible but the answer depends a bit on what exactly you mean by registering a 3 channel stack.Do you have a stack with only 3 images, one per color (3 colors x 1 image) and want to align the colored images with each other?Or do you have a 3-color stack with multiple images per color (3 colors x N images) and want to align the N images within each color to each other (but not the 3 colors)?the N images of one color (e.g. green channel) to each other and then apply this transformation to the other 2 color channels?the N images of the 3 colors with each other using information from all 3 colors "simultaneously"?Gregor—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by glichtner** [comment]
Hi Adriel,

I would propose to register only one channel (the one with the clearest structures) and then apply the transformation to the other channels, like so:
```python
# assuming img has a shape of (frames, width, height, color)
img = io.imread('colored.tif')
reg = np.copy(img)

sr = StackReg(StackReg.RIGID_BODY) # or any other transformation
sr.register_stack(img[:, :, :, 0]) # register using 1st color

for color in range(img.shape[3]):
    reg[:, :, :, color] = sr.transform_stack(img[:, :, :, color]
```

Another potential option could be to aggregate the stack over the colors (i.e. create a grayscale version of the image) and register that stack, then apply the registration to the original stack:

```python
# assuming img has a shape of (frames, width, height, color)
img = io.imread('colored.tif')
img_flat = np.max(img, axis=3) # take maximum over the color channels; could also use np.mean or np.median
reg = np.copy(img)

sr = StackReg(StackReg.RIGID_BODY) # or any other transformation
sr.register_stack(img_flat) # register using 1st color

for color in range(img.shape[3]):
    reg[:, :, :, color] = sr.transform_stack(img[:, :, :, color]
```

Which option works better depends on what you have in the images. If you are aligning photos, you could also use other methods to convert to grayscale, e.g. https://stackoverflow.com/questions/12201577/how-can-i-convert-an-rgb-image-into-grayscale-in-python 

Let me know if that helps.
Gregor

**Comment by machinedheart10** [comment]
Hi Gregor,I have tried your alternate method and it works perfectly. I greatly appreciate your help. Thank you so much. Thank you,Adriel Ho  From: Gregor LichtnerSent: Thursday, 10 December 2020 10:53 pmTo: glichtner/pystackregCc: machinedheart10; AuthorSubject: Re: [glichtner/pystackreg] Coloured tiffs stack registration (#7) Hi Adriel,I would propose to register only one channel (the one with the clearest structures) and then apply the transformation to the other channels, like so:# assuming img has a shape of (frames, width, height, color)img = io.imread('colored.tif')reg = np.copy(img) sr = StackReg(StackReg.RIGID_BODY) # or any other transformationsr.register_stack(img[:, :, :, 0]) # register using 1st color for color in range(img.shape[3]):    reg[:, :, :, color] = sr.transform_stack(img[:, :, :, color]Another potential option could be to aggregate the stack over the colors (i.e. create a grayscale version of the image) and register that stack, then apply the registration to the original stack:# assuming img has a shape of (frames, width, height, color)img = io.imread('colored.tif')img_flat = np.max(img, axis=3) # take maximum over the color channels; could also use np.mean or np.medianreg = np.copy(img) sr = StackReg(StackReg.RIGID_BODY) # or any other transformationsr.register_stack(img_flat) # register using 1st color for color in range(img.shape[3]):    reg[:, :, :, color] = sr.transform_stack(img[:, :, :, color]Which option works better depends on what you have in the images. If you are aligning photos, you could also use other methods to convert to grayscale, e.g. https://stackoverflow.com/questions/12201577/how-can-i-convert-an-rgb-image-into-grayscale-in-pythonLet me know if that helps.Gregor—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
