### ISSUE TITLE
4D Compatibility

### ISSUE THREAD

**Issue by caviri** [glichtner/pystackreg#9]
Hello, Thanks for this great package. It is compatible with 3D + time motion correction? If no, could you suggest another python package for this? Thanks in advance.

**Comment by glichtner** [comment]
Hi,
pystackreg is for 2D image registration only.
I haven't looked into 3D registration other than using SPM (matlab) for MRI data, maybe [dipy](https://dipy.org/documentation/1.0.0./examples_built/affine_registration_3d/) could be useful?
I remember having seen a recently released python package for 3D image registration, but unfortunately I'm not able to find it now.
